name: grinch
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_svg: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg1.svg
    - assets/images/bg1.png
    - assets/images/rgbg.png
    - assets/images/greenbg.png
    - assets/images/grinch.png
    - assets/images/tree.png
    - assets/images/tree_bg.png
    - assets/images/puzzle.png
    - assets/images/checked.svg
    - assets/images/stars_grey.svg
    - assets/images/stars_yellow.svg

  fonts:
    - family: ProximaBold
      fonts:
        - asset: assets/fonts/ProximaNova-Bold.otf
    - family: ProximaRegular
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.otf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
